[workspace]
members = [
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7",
    "day7b",
    "day8",
    "day9",
    "day10",
    "day10b",
    "day11",
    "day11b",
]
